# Generated by Django 2.2.7 on 2019-12-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_club_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='time_of_meeting',
            field=models.DateField(),
        ),
    ]
