# Generated by Django 2.2.7 on 2019-12-17 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_club_app', '0003_auto_20191215_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='rating',
            field=models.CharField(default=5, max_length=1),
            preserve_default=False,
        ),
    ]
