# Generated by Django 2.2.7 on 2019-12-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_club_app', '0004_film_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
